import { Position } from "./types";

export const initialCard = {
  id: "",
  name: "",
  level: 0,
  price: 0,
  tasks: 0,
  duties: {
    sellProducts: false,
    setPrices: false,
    viewAnalytics: false,
    duel: false,
    submitClaims: false,
    purchaseMaterials: false,
    assignWorkers: false,
    assignPositions: false,
    kickOutFromTheGang: false,
  },
};

export const initialDuties = {
  sellProducts: false,
  setPrices: false,
  viewAnalytics: false,
  duel: false,
  submitClaims: false,
  purchaseMaterials: false,
  assignWorkers: false,
  assignPositions: false,
  kickOutFromTheGang: false,
};

export const initialList: Position[] = [
  {
    id: "1",
    name: "Новобранец",
    level: 1,
    price: 50,
    tasks: 0,
    duties: {
      sellProducts: false,
      setPrices: true,
      viewAnalytics: false,
      duel: false,
      submitClaims: false,
      purchaseMaterials: false,
      assignWorkers: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "2",
    name: "Рядовой",
    level: 10,
    price: 80,
    tasks: 5,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      duel: false,
      submitClaims: false,
      purchaseMaterials: false,
      assignWorkers: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "3",
    name: "Сержант",
    level: 10,
    price: 100,
    tasks: 10,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      purchaseMaterials: false,
      assignWorkers: false,
      duel: false,
      submitClaims: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "4",
    name: "Новобранец",
    level: 10,
    price: 50,
    tasks: 10,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      duel: false,
      submitClaims: false,
      purchaseMaterials: false,
      assignWorkers: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "5",
    name: "Рядовой",
    level: 10,
    price: 80,
    tasks: 15,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      duel: false,
      submitClaims: false,
      purchaseMaterials: false,
      assignWorkers: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "6",
    name: "Сержант",
    level: 10,
    price: 100,
    tasks: 20,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      purchaseMaterials: false,
      assignWorkers: false,
      duel: false,
      submitClaims: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "7",
    name: "Новобранец",
    level: 10,
    price: 50,
    tasks: 25,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      duel: false,
      submitClaims: false,
      purchaseMaterials: false,
      assignWorkers: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
  {
    id: "8",
    name: "Новобранец",
    level: 10,
    price: 50,
    tasks: 25,
    duties: {
      sellProducts: false,
      setPrices: false,
      viewAnalytics: false,
      duel: false,
      submitClaims: false,
      purchaseMaterials: false,
      assignWorkers: false,
      assignPositions: false,
      kickOutFromTheGang: false,
    },
  },
];

export const checkboxNames = {
  Торговля: {
    sellProducts: "Продавать продукт",
    setPrices: "Выставлять цены",
    viewAnalytics: "Смотреть аналитику",
  },
  Производство: {
    purchaseMaterials: "Закупать сырье",
    assignWorkers: "Назначать рабочих",
  },
  Разборки: {
    duel: "Дуель",
    submitClaims: "Выставлять претензии",
  },
  Управление: {
    assignPositions: "Назначать должности",
    kickOutFromTheGang: "Выгонять из банды",
  },
};
